-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 15:55:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `Imagem_perfil` BLOB NULL,
  `biografia_usuario` VARCHAR(500) NULL,
  `Portifolio_usuario` VARCHAR(500) NULL,
  `Endereco_usuario` VARCHAR(255) NULL,
  `Telefone_usuario` VARCHAR(45) NULL,
  `Imagem_portifolio` BLOB NULL,
  `Categoria_portifolio` VARCHAR(100) NULL,
  PRIMARY KEY (`idPerfil`),
  UNIQUE INDEX `idPerfil_UNIQUE` (`idPerfil` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `avaliacao_individual` SMALLINT(1) NULL,
  `Media_avaliacao` DECIMAL(1,1) NOT NULL DEFAULT 0,
  `id_usuario_avaliador` INT NULL,
  `id_usuario_avaliado` INT NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`, `Perfil_idPerfil`),
  INDEX `fk_Avaliacao_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  UNIQUE INDEX `idAvaliacao_UNIQUE` (`idAvaliacao` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro` (
  `idCadastro` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(125) NULL,
  `cpf_usuario` VARCHAR(45) NULL,
  `email_usuario` VARCHAR(125) NULL,
  `senha_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idCadastro`),
  UNIQUE INDEX `idCadastro_UNIQUE` (`idCadastro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Avaliacao_idAvaliacao` INT NOT NULL,
  `Cadastro_idCadastro1` INT NOT NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `Avaliacao_idAvaliacao`, `Cadastro_idCadastro1`, `Perfil_idPerfil`),
  INDEX `fk_Usuario_Avaliacao1_idx` (`Avaliacao_idAvaliacao` ASC) VISIBLE,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Cadastro2_idx` (`Cadastro_idCadastro1` ASC) VISIBLE,
  INDEX `fk_Usuario_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Avaliacao1`
    FOREIGN KEY (`Avaliacao_idAvaliacao`)
    REFERENCES `mydb`.`Avaliacao` (`idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Cadastro2`
    FOREIGN KEY (`Cadastro_idCadastro1`)
    REFERENCES `mydb`.`Cadastro` (`idCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chat` (
  `idChat` INT NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(100) NULL,
  `data_mensagem` DATETIME NULL,
  `Usuario_id_remetente` INT NOT NULL,
  `Usuario_Avaliacao_remetente` INT NOT NULL,
  `Usuario_id_destinatario` INT NOT NULL,
  `Usuario_Avaliacao_destinatario` INT NOT NULL,
  PRIMARY KEY (`idChat`, `Usuario_id_remetente`, `Usuario_Avaliacao_remetente`, `Usuario_id_destinatario`, `Usuario_Avaliacao_destinatario`),
  INDEX `fk_Chat_Usuario1_idx` (`Usuario_id_remetente` ASC, `Usuario_Avaliacao_remetente` ASC) VISIBLE,
  INDEX `fk_Chat_Usuario2_idx` (`Usuario_id_destinatario` ASC, `Usuario_Avaliacao_destinatario` ASC) VISIBLE,
  UNIQUE INDEX `idChat_UNIQUE` (`idChat` ASC) VISIBLE,
  CONSTRAINT `fk_Chat_Usuario1`
    FOREIGN KEY (`Usuario_id_remetente` , `Usuario_Avaliacao_remetente`)
    REFERENCES `mydb`.`Usuario` (`id_usuario` , `Avaliacao_idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_Usuario2`
    FOREIGN KEY (`Usuario_id_destinatario` , `Usuario_Avaliacao_destinatario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario` , `Avaliacao_idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feed` (
  `idFeed` INT NOT NULL AUTO_INCREMENT,
  `Imagem_feed` BLOB NULL,
  `Descricao_feed` VARCHAR(30) NULL,
  `Usuario_id_usuario` INT NOT NULL,
  `Usuario_Avaliacao_idAvaliacao` INT NOT NULL,
  `Usuario_Cadastro_idCadastro1` INT NOT NULL,
  `Usuario_Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idFeed`, `Usuario_id_usuario`, `Usuario_Avaliacao_idAvaliacao`, `Usuario_Cadastro_idCadastro1`, `Usuario_Perfil_idPerfil`),
  INDEX `fk_Feed_Usuario1_idx` (`Usuario_id_usuario` ASC, `Usuario_Avaliacao_idAvaliacao` ASC, `Usuario_Cadastro_idCadastro1` ASC, `Usuario_Perfil_idPerfil` ASC) VISIBLE,
  UNIQUE INDEX `idFeed_UNIQUE` (`idFeed` ASC) VISIBLE,
  CONSTRAINT `fk_Feed_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario` , `Usuario_Avaliacao_idAvaliacao` , `Usuario_Cadastro_idCadastro1` , `Usuario_Perfil_idPerfil`)
    REFERENCES `mydb`.`Usuario` (`id_usuario` , `Avaliacao_idAvaliacao` , `Cadastro_idCadastro1` , `Perfil_idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;